# Generated by Django 5.2.9 on 2026-02-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dns', '0001_squashed_netbox_dns_0_22'),
        ('netbox_plugin_bind_provisioner', '0002_alter_integerkeyvaluesetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogZoneMemberIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=26, unique=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_provisioner_models', to='netbox_dns.zone')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
