# Generated by Django 5.2.9 on 2026-02-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dns', '0001_squashed_netbox_dns_0_22'),
        ('netbox_plugin_bind_provisioner', '0004_alter_catalogzonememberidentifier_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogzonememberidentifier',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catz_identifier', to='netbox_dns.zone'),
        ),
    ]
